wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.19.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746229436
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      - 62
      4: 3.13.2
      5: 0.19.10
      8:
      - 5
      13: darwin-arm64
wandb_project:
  desc: null
  value: Bi-level GFlowNet Training
data_path:
  desc: null
  value: data/data.pickle
batch_size:
  desc: null
  value: 149
num_epochs:
  desc: null
  value: 7
embedding_dim:
  desc: null
  value: 103
hidden_dim:
  desc: null
  value: 406
lr_ac:
  desc: null
  value: 0.01517311690918378
lr_cr:
  desc: null
  value: 0.0007167145861554725
mom_ac:
  desc: null
  value: 0.4879223716963468
mom_cr:
  desc: null
  value: 0.42771162844570326
penalty_weight:
  desc: null
  value: 1.0
cut_interval:
  desc: null
  value: 50
log_interval:
  desc: null
  value: 10
log_dir:
  desc: null
  value: runs
model_version:
  desc: null
  value: v1
