wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.13.2
    cli_version: 0.19.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746229249
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 14
      - 16
      - 23
      - 37
      - 62
      4: 3.13.2
      5: 0.19.10
      8:
      - 5
      13: darwin-arm64
wandb_project:
  desc: null
  value: Bi-level GFlowNet Training
data_path:
  desc: null
  value: data.pickle
batch_size:
  desc: null
  value: 76
num_epochs:
  desc: null
  value: 20
embedding_dim:
  desc: null
  value: 186
hidden_dim:
  desc: null
  value: 628
lr_ac:
  desc: null
  value: 0.00247314453387641
lr_cr:
  desc: null
  value: 0.0005810749481737045
mom_ac:
  desc: null
  value: 0.554776735271606
mom_cr:
  desc: null
  value: 0.7651546648265404
penalty_weight:
  desc: null
  value: 1.0
cut_interval:
  desc: null
  value: 50
log_interval:
  desc: null
  value: 10
log_dir:
  desc: null
  value: runs
model_version:
  desc: null
  value: v1
